import { ScheduleEvent } from "./ScheduleEvent";

/**
 * Holds the data for events shown on the Schedule Page
 */
export const events: ScheduleEvent[] = [ // PLACEHOLDERS: Update all event times, descriptions, and locations as they are finalized
  {
    id: 1,
    title: "Check-in Table",
    description: "Your first stop to kick off the weekend! The check-in table will be open from 9am-8pm to accomadate attendees arriving in Rochester on Friday. Stop by at any time to pick up your badge, swag bag, and other event materials. Ask questions about the weekend's events and chat with CSHers.",
    date: "Friday, April 10, 2026",
    time: "9:00 AM - 8:00 PM",
    location: "TBD", // PLACEHOLDER: Confirm location
    address: "TBD",
    capacity: "All attendees",
    dressCode: "Casual",
    type: "social",
  },
  {
    id: 2,
    title: "Campus & Floor Tours",
    description: "See how CSH has evolved over the years with guided tours of the floor conducted by current CSHers. Our tour guides can also show you around RIT's campus to highlight some of the changes over the years. Tours will run every 30 minutes, originating from the check-in table.",
    date: "Friday",
    time: "9:00 AM - 8:00 PM",
    location: "TBD", 
    address: "TBD",
    capacity: "All attendees",
    dressCode: "Casual",
    type: "activity",
  },
  {
    id: 3,
    title: "Photo Hunt Starts",
    description: "Retrieve a photohunt packet during check-in and participate in a time-old CSH tradition! Our special 50th Photohunt packet includes clues from all 50 years of CSH history. Photohunt will kick-off and conclude asynchronously, information will be provided on how to submit your photos. While we will show off some of the best photos at the end of the weekend, 50th Anniversary Photohunt will not be officially judged, so just focus on taking fun pictures!",
    date: "Friday, April 10, 2026",
    time: "9:00 AM - 10:00AM",
    location: "Asynchronous", 
    address: "N/A",
    capacity: "All attendees",
    dressCode: "",
    type: "activity",
  },
  // {
  //   id: 4,
  //   title: "Lunch",
  //   description: "",
  //   date: "Friday, April 10, 2026",
  //   time: "12:00 PM - 2:00 PM",
  //   location: "TBD", // PLACEHOLDER: Confirm location
  //   address: "TBD",
  //   capacity: "Open to all attendees",
  //   dressCode: "Casual",
  //   type: "food",
  // },
  {
    id: 5,
    title: "Open Sauce Mixer",
    description: "TICKETED EVENT! Take in the best of CSH with a unique preview of our current projects and displays! Funds raised from this event support CSH's participation in the 2026 Open Sauce convention hosted in San Francisco. Enjoy a Rochester staple: garbage plates catered by Dogtown. ",
    date: "Friday, April 10, 2026",
    time: "6:30 PM - 8:30 PM",
    location: "Douglass Sprague Perry Hall (DSP) Room 1250", 
    address: "43 Greenleaf Ct, Rochester, NY 14623",
    capacity: "All attendees",
    dressCode: "Casual",
    type: "activity",
  },
  {
    id: 6,
    title: "After Hours Mixer",
    description: "Join us in the upstairs event room at the Daily Refresher for an evening hang and custom CSH cocktails! Note: this event is 21+ only!",
    date: "Friday, April 10, 2026",
    time: "8:30 PM - 11:00 PM",
    location: "The Daily Refresher (Upstairs)",
    address: "293 Alexander St Rochester, NY 14607",
    capacity: "All attendees",
    dressCode: "Nightime dressy",
    type: "social",

  },
  {
    id: 7,
    title: "Check-in Table",
    description: "The check-in table will be available from 9am-1pm to accomadate attendees arriving in Rochester on Saturday. Stop by at any time to pick up your badge, swag bag, and event materials. Ask questions about the weekend's events and chat with CSHers.",
    date: "Saturday, April 11, 2026",
    time: "9:00 AM - 1:00 PM",
    location: "TBD", // PLACEHOLDER: Confirm location
    address: "TBD",
    capacity: "All attendees",
    dressCode: "Casual",
    type: "social",
  },
  {
    id: 8,
    title: "Campus & Floor Tours",
    description: "See how CSH has evolved over the years with guided tours of the floor conducted by current CSHers. Our tour guides can also show you around RIT's campus to highlight some of the changes over the years. Tours will run every 30 minutes, originating from the check-in table.",
    date: "Saturday, April 11, 2026",
    time: "9:00 AM - 1:00 PM",
    location: "CSH, DSP Floor 3", 
    address: "43 Greenleaf Ct, Rochester, NY 14623",
    capacity: "All attendees",
    dressCode: "Casual (comfortable walking shoes)",
    type: "activity",
  },
  // {
  //   id: 9,
  //   title: "Lunch",
  //   description: "",
  //   date: "Saturday, April 11, 2026",
  //   time: "12:00 PM - 2:00 PM",
  //   location: "TBD", // PLACEHOLDER: Confirm location
  //   address: "",
  //   capacity: "",
  //   dressCode: "",
  //   type: "food",
  // },
  // {
  //   id: 10,
  //   title: "Dismiss for Dinner",
  //   description: "",
  //   date: "Saturday, April 11, 2026",
  //   time: "1:00 PM - 3:30 PM",
  //   location: "TBD", // PLACEHOLDER: Confirm location
  //   address: "Rochester Institute of Technology",
  //   capacity: "",
  //   dressCode: "",
  //   type: "social",
  // },
  {
    id: 11,
    title: "Bus Runs To The Wintergarden",
    description: "A free bus is available to transport you to the Wintergarden for our formal dinner. The bus will stop at RIT, the Courtyard by Marriott Rochester Brighton, and the Hampton Inn & Suites Rochester/Henrietta. The busses will take multiple rounds.",
    date: "Saturday, April 11, 2026",
    time: "3:30 PM - 5:00 PM",
    location: "Multiple locations", 
    address: "",
    capacity: "",
    dressCode: "",
    type: "social",
  },
  {
    id: 12,
    title: "CSH 50th Dinner",
    description: "TICKETED EVENT! The highlight of the weekend! Join us for an elegant formal dinner celebrating 50 years of CSH. Enjoy a delicious meal, keynote speeches from notable alumni, awards ceremony honoring CSH's legacy, and plenty of time to reconnect with friends.",
    date: "Saturday, April 11, 2026",
    time: "5:00 PM - 10:00 PM",
    location: "Wintergarden", 
    address: "1 Bausch and Lomb Pl, Rochester, NY 14604",
    capacity: "All attendees",      
    dressCode: "Cocktail Semi Formal",
    type: "main",
  },
  {
    id: 13,
    title: "Photo Hunt Ends",
    description: "",
    date: "Saturday, April 11, 2026",
    time: "5:00 PM - 6:00 PM",
    location: "Asychronous", 
    address: "N/A",
    capacity: "All attendees",
    dressCode: "",
    type: "activity",
  },
  // {
  //   id: 14,
  //   title: "Showcase of Photo Hunt (Not Judged)",
  //   description: "",
  //   date: "Saturday, April 11, 2026",
  //   time: "6:00 PM - 8:00 PM",
  //   location: "The Wintergarden", // PLACEHOLDER: Confirm location
  //   address: "TBD, Rochester, NY",
  //   capacity: "",
  //   dressCode: "",
  //   type: "activity",
  // },
  {
    id: 15,
    title: "Bus Run Back To Campus",
    description: "A free bus is available to transport you back after our formal dinner. The bus will pick you up from Wintergarden and stop at RIT, the Courtyard by Marriott Rochester Brighton, and the Hampton Inn & Suites Rochester/Henrietta. The busses will complete one singular round at the end of the event.",
    date: "Saturday, April 11, 2026",
    time: "10:00 PM - 11:00 PM",
    location: "The Wintergarden", // PLACEHOLDER: Confirm location
    address: "",
    capacity: "",
    dressCode: "",
    type: "social",
  },
  {
    id: 16,
    title: "Farewell Party at Swillburger",
    description: "TICKETED EVENT! Before you head home, join us for a farewell brunch. Last chance to exchange contact info, take group photos, and say your goodbyes. Ticket packages include options for open bar, food, and play tokens.",
    date: "Sunday, April 12, 2026",
    time: "11:00 AM - 2:00 PM",
    location: "Swillburger/Playhouse", 
    address: "820 South Clinton, Rochester, NY 14620",
    capacity: "All attendees",
    dressCode: "Casual",
    type: "food",
  },
  {
    id: 19,
    title: "Mechanical Keyboard Meetup",
    description: "CSHers will be showing off their mechnical keyboard setups! Stop by to check it out and spend some time learning about keyboards. There will be special guests and giveaways!",
    date: "Friday, April 10, 2026",
    time: "12:30 PM - 2:00 PM",
    location: "Douglass Sprague Perry Hall (DSP) Room 1250", // Confirm location
    address: "43 Greenleaf Ct, Rochester, NY 14623",
    capacity: "All attendees",
    dressCode: "Casual",
    type: "activity",
  },
  {
    id: 17,
    title: "IGM Symposium",
    description: "https://www.rit.edu/computing/school-interactive-games-and-media/ims",
    date: "Saturday, April 11, 2026",
    time: "10:00 AM - 5:00 PM",
    location: "RIT's MAGIC Spell Studios", // Confirm location
    address: "1 Lomb Memorial Dr, Rochester, NY",
    capacity: "",
    dressCode: "",
    type: "external",
  },
  {
    id: 18,
    title: "RIT Accepted Student Open House",
    description: "https://www.rit.edu/admissions/accepted-open-house",
    date: "Saturday, April 11, 2026",
    time: "8:00 AM - 3:30 PM",
    location: "RIT",
    address: "1 Lomb Memorial Dr, Rochester, NY",
    capacity: "",
    dressCode: "",
    type: "external",
  }
]